apiVersion: v1
kind: Pod
metadata:
  name: stikked
spec:
  volumes:
  - name: db-volume
    hostPath:
      path: /home/xiaodong/dbdata2
      type: Directory
  containers:
  - name: db
    image: mariadb
    command:
    - docker-entrypoint.sh
    - mysqld
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: i10vep0d
    - name: MYSQL_DATABASE
      value: stikked
    - name: MYSQL_USER
      value: stikked
    - name: MYSQL_PASSWORD
      value: stikked
    volumeMounts:
    - name: db-volume
      mountPath: /var/lib/mysql
  - name: web
    image: claudehohl/stikked
    command:
    - docker-php-entrypoint
    - apache2-foreground
    env:
    - name: STIKKED_SITE_NAME
      value: Stikked
    - name: STIKKED_BASE_URL
      value: http://127.0.0.1:8001/
    - name: STIKKED_DB_HOSTNAME
      value: 127.0.0.1
    ports:
    - containerPort: 80
      hostPort: 8001
      protocol: TCP
